# Generated by Django 3.1.2 on 2020-11-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_lyricnotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneticNotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('line', models.IntegerField()),
                ('offset', models.IntegerField()),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
    ]
